### PR TITLE
Added path to check for config, removing dependencey on a file in the…

### PR DESCRIPTION
**Pull request by poundbangbash**
… webroot. Allows for git management of custom config.php.

Since the common (preferred?) way to install munkireport is via git clone, this PR adds checking for a config.php in /custom/config/config.php as well. This will allow admins to manage a git repo on custom/config/ to version their preference file as well.

This first checks for config.php in /. If it finds it it loads and doesn't continue processing.  If the first check fails, it checks the /custom/config/ directory, if that fails then it errors out.

### CODE REVIEW

**Comment by bochoven** [comment]
I don't want to pin the location of an alternative config file to `APP_ROOT . "/custom/config/" . "config.php"`. And I am not sure what a sane alternative is.

**Comment by poundbangbash** [comment]
How about a way to specify where the config should be similar to the App Settings in the config_defualt.php. Setting just the preference in the webroot config.php that directs where to find the full config.php.

/Config.php -> conf['config_path'] = "/admin/provided/path";

That's a bit messy to have a proxy config file but since the webroot location is the only default I don't see a way to set where the config should be found otherwise. 

I suppose a symlink would accomplish the same effect assuming the symlink would be followed. 

-Eric

**Comment by bochoven** [comment]
You can accomplish the same by making `config.php` look like this: 

```php
<?php require '/admin/provided/path';
```

We could/should add that to the wiki as a way to securely store the config.

**Comment by bochoven** [comment]
Added documentation here https://github.com/munkireport/munkireport-php/wiki/Secure-config.php

**Pull request closed without merging**
