### PR TITLE
Add Launch Daemons module

### PR DESCRIPTION
**Pull request by tuxudo**
Gets data about Launch Daemons and Launch Agents on in the /Library/
and /Users/Library folders.

### CODE REVIEW

**Comment by bochoven** [comment]
That's a lot of columns..
I have as suggestion: only make columns for fields that should be commonly searched/displayed in a widget, etc, store the rest as json in a text column.

**Comment by tuxudo** [comment]
I think I can do that. I'll give it a try at least.

**Comment by ofirgalcon** [comment]
Works although I'm trying to think of a better way of displaying this. Maybe collapsible folders?

**Comment by tuxudo** [comment]
Not yet ready for merging, planning on reworking some of this.

**Comment by tuxudo** [comment]
Closing PR, moved to module repo

**Pull request closed without merging**
