### PR TITLE
Update fr.json

### PR DESCRIPTION
**Pull request by lolipale**
Some spelling corrections and add new report menu (location report)

### CODE REVIEW

**Comment by bochoven** [comment]
Thanks! Could I point you to https://github.com/munkireport/munkireport-php/wiki/Localizing#translation-tool ? This will aid in quickly finding translatable items. The tool was offline but is now in working order again.

**Comment by lolipale** [comment]
Hello,
Could you give me an advice to get the entire keys of munkireport-php ?
I realize that in fact lack some keys in the file fr.json,
Thanks you very much for all your (very good) job !

**Comment by bochoven** [comment]
en.json contains all kets

**Comment by bochoven** [comment]
Keys

**Pull request merged**
