### PR TITLE
Re-Did Kene101 Power Module

### PR DESCRIPTION
**Pull request by dingerkingh**
I rebuilt kene101’s power module. However, the client_detail.php code
in the WIP was much different than the code of the current version.
This code works with the current 2.2.0 - but not haven’t been able to
test on the WIP. All that was throwing me is that I don’t see the
bluetooth tab-pane anymore.

### CODE REVIEW

**Comment by bochoven** [comment]
I think you need to update your repository. It is very behind the current munkireport repo. See https://help.github.com/articles/syncing-a-fork/

**Comment by dingerkingh** [comment]
Ugh - I am a git moron.

**Comment by kene101** [comment]
> Ugh - I am a git moron.
> 
My problem too.

Does this mean the Power Module has been completed?


My apologies and embarrassment for starting, and receiving Arjen’s good advice & comment and not completing.


If not complete I will continue.

Regards Ken

**Comment by bochoven** [comment]
Hi ken, your changes have been pulled and merged here: #205. Thanks!

**Pull request closed without merging**
