### PR TITLE
Computer Cleanup Implement

### PR DESCRIPTION
**Pull request by computeronix**
Implements the ability to run a cleanup anytime the URL is accessed (regardless of user authorization)

http://munkireport-url/index.php?/cleanup/machine_cleanup

By default in the config, this is disabled

To enable make clean_days greater than 0 where the value is anything x days and older from the time the script is run will be removed

### CODE REVIEW

**Comment by computeronix** [comment]
Added orphan record support

Whenever the above page is accessed; it will review the entire table list serial numbers (where applicable) and if it does not have an associated record in munkireport table then remove it.

**Comment by computeronix** [comment]
Takes care of https://github.com/munkireport/munkireport-php/issues/291

**Comment by bochoven** [comment]
I can't merge this, I think the issue has to be solved differently:

- I don't want duplicate code that deletes a machine, so
- The current delete_machine routine needs to be moved to a library
- I have been working on a cron-like mechanism in munkireport to do maintenance tasks
- This would need to be able to fit in that mechanism (I know I have to flesh that out)
- I would not use subqueries in each table: just collect all out-of-date serials using one query and then loop over those calling the delete_machine routine.
- I'm not sure what the 'orphan' cleaning is about, I haven't seen that in my env.

-Arjen

**Comment by computeronix** [comment]
No problem; feel free to use the queries as needed to pull what is needed

Orphan occasionally I have had an orphaned record if the device was removed by "other means"

**Comment by OldManWarren** [comment]
Can I implement this in an existing instance of munkireport?  If so where would I start?

**Pull request closed without merging**
