### PR TITLE
location - Fix mysql error with strict tables

### PR DESCRIPTION
**Pull request by clburlison**
Basically if the key is empty don't attempt to write an empty string.

This only affects MySQL users who have `STRICT_TRANS_TABLES` enabled however as of version 5.7.5 this is the default value.

### CODE REVIEW

**Comment by bochoven** [comment]
Ok, but this would retain the previous value. Not sure this is a real world problem.

**Comment by clburlison** [comment]
Ew. I'm not sure if that would be a problem either. In slack you mentioned.
> You could remove the automatic retrieving of values when instantiating the model

If that sounds like a better solution I'd need guidance on what you mean.

**Comment by bochoven** [comment]
```php

<?php
class Location_model extends Model {
	
	// Defaults array
	private $defaults = array();

	function __construct($serial='')
	{
		parent::__construct('id', 'location'); //primary key, tablename
		$this->rs['id'] = '';
		$this->rs['serial_number'] = $serial; $this->rt['serial_number'] = 'VARCHAR(255) UNIQUE';
		$this->rs['address'] = '';
		$this->rs['altitude'] = 0;
		$this->rs['currentstatus'] = '';
		$this->rs['ls_enabled'] = 0;
		$this->rs['lastlocationrun'] = '';
		$this->rs['lastrun'] = '';
		$this->rs['latitude'] = 0.0;
		$this->rs['latitudeaccuracy'] = 0;
		$this->rs['longitude'] = 0.0;
		$this->rs['longitudeaccuracy'] = 0;
		$this->rs['stalelocation'] = '';
		
		// Store default values
		$this->defaults = $this->rs;
		
		// Add indexes
		$this->idx[] = array('address');
		$this->idx[] = array('currentstatus');

		// Schema version, increment when creating a db migration
		$this->schema_version = 1;
		
		// Create table if it does not exist
		$this->create_table();
		
		if ($serial)
		{
			$this->retrieve_record($serial);
		}
		
		$this->serial = $serial;
		  
	}
	
	// ------------------------------------------------------------------------

	/**
	 * Process data sent by postflight
	 *
	 * @param string data
	 * 
	 **/
	function process($data)
	{		
		require_once(APP_PATH . 'lib/CFPropertyList/CFPropertyList.php');
		$parser = new CFPropertyList();
		$parser->parse($data);
		
		$plist = $parser->toArray();
		
		// Translate location strings to db fields
		$translate = array(
			'Address' => 'address',
			'Altitude' => 'altitude',
			'CurrentStatus' => 'currentstatus',
			'GoogleMap' => 'googlemap',
			'LS_Enabled' => 'ls_enabled',
			'LastLocationRun' => 'lastlocationrun',
			'LastRun' => 'lastrun',
			'Latitude' => 'latitude',
			'LatitudeAccuracy' => 'latitudeaccuracy',
			'Longitude' => 'longitude',
			'LongitudeAccuracy' => 'longitudeaccuracy',
			'StaleLocation' => 'stalelocation');

		// Parse data
		foreach($translate as $search => $field) {
			    
			if (isset($plist[$search]))
			{
				$this->$field = $plist[$search];
			}
			else
			{
				$this->$field = $this->defaults[$field];
			}
		}		
				    
		$this->save();
	}
}
```

**Comment by clburlison** [comment]
Thanks for the sample code. Your solution is much better. I've updated this PR with the requested changed and tested on MySQL 5.7.11 without issue.

**Comment by bochoven** [comment]
Thanks!

**Pull request merged**
