### PR TITLE
Power Module

### PR DESCRIPTION
**Pull request by kene101**
Battery Information

### CODE REVIEW

**Comment by dingerkingh** [comment]
What is the status of this pull request? Would love to have this feature.

**Comment by bochoven** [comment]
@kene101 it looks like some other commits got mixed in with this PR. Do you have time to clean it up/do it again?

**Comment by dingerkingh** [comment]
I actually created another pull request with all of his files and a few changes that I found. No sure how active he is as he hasn't been on in a couple months so I thought I would get the ball rolling.

**Comment by bochoven** [comment]
Closed in favour of #205

**Pull request closed without merging**
