### PR TITLE
reCaptcha Support

### PR DESCRIPTION
**Pull request by computeronix**
Added Support for reCaptcha

In the config just enter the public and private keys if you want to use it otherwise leave them blank

### CODE REVIEW

**Comment by bochoven** [comment]
I get some errors using this:

```
Warning: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed in /Users/Shared/munkireport-php/app/controllers/auth.php on line 65

Warning: file_get_contents(): Failed to enable crypto in /Users/Shared/munkireport-php/app/controllers/auth.php on line 65

Warning: file_get_contents(https://www.google.com/recaptcha/api/siteverify?secret=6Lc0sCcTAAAAALpCnq0OT8ot7y2p-gVgHiqTy38X&response=03AHJ_VutsoVRinap9xxE1mt-r6R2NCJNV2nECif3oOxIgoJD7YqOSW3bJt-IVIxbNaQ26ND928z0wSeNQReynX2GKWgsmSlQ0KcrYzQ4g9EmmWdcFBYqfCOKPN-Ljdbil31nK-oK7snzBd5oh62Ab4835nXoFOPUF6luTyKHjTuNDPlhYnB2op9scj58uXRoNEknq-zg8imuJqO9iNFd3I3cgqXIIBm4Fm5KAvJTvL-8VXYGMGUbrOeWwLvZWUemDsPfrWxJtOC4fhMJiAVVT6akIsca1V0HwRI2XREZL0IH35_98dCwT-8gTp0Fcy9AbqE3Hngr9uhiRvleypYD_tChlavR4zGI0eGBM9GhPow2MRDxxGkHYb8AzoJnunOzuvCCoftqSYKwiwgFcMbXlUnn2xFJ7IB-xTlAfjedZ_YluREMfyoHLuQTnC2OF9o4lzuGS9NykgacSs-eg-6ys4cM-CgvHMBOxiU2B1mBKr1f9nZfof15Uh_r8ROW0rlKIc1DWg6yBffjFJrOPIiKTqN0GR2gLjD7895GKNFnY28x_3O62CZeHc2zKHkA41qDamDC61dp6EkMbj0-5rKjEZWfFlwbvhKA11SsdiW8Yy1t9D95hg8l1uyx9H4eWb4-NbhRLo0jkTcgFjNykoKvPT6wc3Y-CUt8yX6blEBC_gihgJWw-qEvWTZx20mGVmGed8izS7vnwbWt1Ntt96ivzKF2QCeJYjGa6Tlmp58he8_esycNAoGi7utogPPxTGLKMhmopUzV906NEMTCWlWi4pWPmBI3Y3W1izeEUnwzymDv8bE_ygAUHnKuokoUWY0QOGu_IOSqC8IGx6gJ5ORUu-VMVy89TGURmcZFGZlG2flqjga11DjRUJM1jjAgXmBt in /Users/Shared/munkireport-php/app/controllers/auth.php on line 65
```

**Comment by computeronix** [comment]
checking now - interesting

i may have assumed https       reviewing that part now

**Comment by computeronix** [comment]
Made some auth.php changes for admins that don't enable it

checking on SSL issue reported

**Comment by computeronix** [comment]
Without causing a security hole
Does your PHP version have cURL installed?

On linux: sudo apt-get install php5-curl

Windows enable the curl extension

Otherwise we can put this in the script which is a security hole (minor one) but will work

$arrContextOptions=array(
    "ssl"=>array(
        "verify_peer"=>false,
        "verify_peer_name"=>false,
    ),
);  

Let me know what you would like to do

**Comment by gmarnin** [comment]
My php version does have curl enabled. Minor security holes turn into big security holes overnight and aren't an option in my environment.

**Comment by computeronix** [comment]
Agree with you there  :)    Hmm thanks for checking;  I tested this on PHP 5.6.x Windows box   digging more      seems to be common across the board ; we do have the option to specify the ssl cert itself and can probably just inject it in the folder;    reviewing this option

**Comment by computeronix** [comment]
Try now added a cacert.pem file that goes in a specific directory

then modified the code per http://stackoverflow.com/questions/33849880/recaptcha-file-get-contents-ssl-operation-failed

FYI the cacert.pem was acquired from the site: http://curl.haxx.se/ca/cacert.pem

**Comment by computeronix** [comment]
Made a change to the view of login.php to look better on smaller devices too (changed offset of button from 3 to 2)

**Comment by gmarnin** [comment]
What's your motivation for adding a reCaptcha?

**Comment by computeronix** [comment]
Help protect against bots

Especially since our instance is linked to LDAP - AD and publicly accessible

**Comment by bochoven** [comment]
Still the same error. I'm running version 5.6.23 on my local macOS machine as in https://github.com/munkireport/munkireport-php/wiki/Quick-demo

**Comment by computeronix** [comment]
Interesting, spinning up a mac vm to test with and will get back to here

**Comment by bochoven** [comment]
Maybe also take a look at https://github.com/google/recaptcha

**Comment by computeronix** [comment]
Ok heavily changed the auth.php code and removed the SSL folder not needed

Also switched everything to post requests per Google Recommendation

tested on Mac OS X using the quick test guide
tested on Windows with https and works too

**Comment by computeronix** [comment]
modified result != 1

Result is actually going to be 1 if it succeeds otherwise blank for anything else

**Comment by bochoven** [comment]
Still the same error for me. (macOS 10.12, php --version
PHP 5.6.23 (cli) (built: Jul 22 2016 19:05:30) )

**Comment by computeronix** [comment]
On the dev instance you added SSL cert correct?  if so  do you have quick instructions on adding a test one to the machine?  otherwise can dig into that

**Comment by bochoven** [comment]
I just pulled your branch and ran that with my reCaptcha credentials in config.php. I did nothing more to get it working.

**Comment by computeronix** [comment]
interesting let me try pulling my branch again and try again  maybe a weird character or something when copying the code over to github    have seen that before

**Comment by gmarnin** [comment]
I tested it without ssl and it's working. 10.11.6, php 5.5.36

**Comment by computeronix** [comment]
thanks for confirming!     i used just http on the mac machine (followed the dev setup) and then tested with and without https on a windows production server

let me figure out loading an ssl cert into a test mac machine and test away there

**Comment by computeronix** [comment]
installed mamp pro (https://www.mamp.info/en/) (using PHP 5.6.10  OS X 10.11.6) and setup ssl with a self-sign cert and left all defaults   and it works fine in https and http

can someone send me a list of php modules installed and i will check against my list to see if one is missing

**Comment by computeronix** [comment]
to rule out google keys too this is the test keys i tested against to check they would work   (then i used my own production keys too)

With the following test keys, you will always get No CAPTCHA and all verification requests will pass.

Site key: 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
Secret key: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
The reCAPTCHA widget will show a warning message to claim that it's only for testing purpose. Please do not use these keys for your production traffic.

https://developers.google.com/recaptcha/docs/faq

**Pull request merged**
