### PR TITLE
GSX Integration

### PR DESCRIPTION
**Pull request by tuxudo**
Integrates GSX via filipp's gsxlib to provide warranty lookups. Includes widget, listing, and client tab. Designed for drop in replacement of the warranty module.

### CODE REVIEW

**Comment by bochoven** [comment]
Thanks! I would like you to change some stuff before I can merge:

- [ ] move the gsx library to lib
- [ ] move the database queries from the widget to the gsx_model
- [ ] fetch the widget data via a JSON call
- [ ] fetch the client tab data via a JSON call instead of rendering directly in the page
- [ ] could you supply a sample gsx.txt file for testing

**Comment by tuxudo** [comment]
Requested changes have been made. I am unable to fetch the client tab data via a JSON call. That is beyond my skill at this time. Ground work is there, but I am unable to get it to render properly.

**Comment by bochoven** [comment]
Ok, could you lowercase the database fields (which would be necessary if we ever add PostgreSQL as backend)?

**Comment by tuxudo** [comment]
Database fields have been made lowercase and GSX database sample data has been created and added to GSX module directory. Created potential fix for issue #377

**Comment by bochoven** [comment]
Thanks for the sample data, but I was looking for somewhat simpler: as I don't have access to GSX, I would like a sample /cache/gsx.txt file that I could drop in and run postflight on so it could populate the database.

**Comment by bochoven** [comment]
Oh and maybe don't fix unrelated issues in one PR, please file a separate PR for each issue. Otherwise I need to cherrypick commits if I don't agree with a particular change but want to merge the rest.

**Comment by tuxudo** [comment]
The /cache/gsx.txt only contains the date of when the lookup was last run. Similar to how the warranty module lookup works.

**Comment by bochoven** [comment]
Ah, ok! Not very useful then

**Comment by bochoven** [comment]
Thanks!

**Pull request merged**
