### PR TITLE
Update fr.json

### PR DESCRIPTION
**Pull request by lolipale**
Update for french translation

### CODE REVIEW

**Comment by bochoven** [comment]
Thanks, but do you mean to commit a new file? 

`assets/locales/20160613_fr.json`

**Comment by lolipale** [comment]
hello,
I make a mistake... I want to update the fr.json file but I had to miss a step ... I'm not very comfortable with these "pull request"

**Comment by bochoven** [comment]
I think you can just change your files

**Comment by bochoven** [comment]
Or close this one and make a new request

**Pull request closed without merging**
