### PR TITLE
Issue 178 - Sort Managed Insalls List

### PR DESCRIPTION
**Pull request by dingerkingh**
I created a function in the munkireport model to sort the associative
array $report[$report_key]. it will sort by display name if available
and then name if it isn’t.

### CODE REVIEW

**Comment by dingerkingh** [comment]
I did a merge from your upstream master - is it normal for all those "Merge remote-tracking branch 'upstream/master' into wip" lines to show up in the pull request?

**Comment by dingerkingh** [comment]
Also - not entirely sure why 
 Arjen van Bochoven	More robust integer_toversion js	 2ac7e9c
 Arjen van Bochoven	Fix migration	 1bec9b6
 Arjen van Bochoven	Merge branch 'bug fix'

is showing up in my pull request either?

**Comment by bochoven** [comment]
Not sure about the merge issues, but you should pull against the wip branch, not against master.

Apart from that, I think it would be better to use dataTables for sorting on the Managed Installs table. That way, you can also search a potentially large table. See the inventory_items_tab

**Comment by dingerkingh** [comment]
Closing pull request because I have no idea how to fix the merge issues- so redo using dataTables as well.

**Pull request closed without merging**
