### PR TITLE
Wip  Testing: Hangs on client page

### PR DESCRIPTION
**Pull request by adambarnett52**
Hi 

I've been testing the WIP branch as there are so very nice new shiny feature ( thanks all for them) 
But when i click on a client the page hangs trying to load, i have to stop to loading of the page to see the data

I suspect it is doing a look up on-line and as we dont have internet access it is failing 

Any suggestions

Thanks
Adam

### CODE REVIEW

**Comment by clburlison** [comment]
@adambarnett52 I'm going guess you meant to  create an Issue and not a Pull Request?

And just for clarification on your munki report server you have no internet access, correct? If that is the case I believe the location module is what will be causing the issue as it's reaching out to https://maps.googleapis.com/maps/api/js?v=3.exp to draw the map. I didn't test no internet access on the server when building that module so additional code will need to be written.

**Comment by gmarnin** [comment]
Which browser? Does it occur with other browsers?

**Comment by adambarnett52** [comment]
Yup. Happened on all browsers 

Sorry meant to make a issue not a PR

**Comment by bochoven** [comment]
Not sure what you mean, we don't have internet access. Do you mean the computer you're using to view munkireport does not connect to the internet?
I don't think the issue is the google maps lookup, if I blackhole maps.googleapis.com, the client page still loads (without a map).

**Comment by bochoven** [comment]
Could you take a look in the web inspector of your browser what is causing the delay? The network tab may prove useful.

**Comment by adambarnett52** [comment]
Sure will check on Monday. 
I meant both client and server do not have access to the Internet. Everything is internal

**Comment by bochoven** [comment]
I have no idea why this auto closed, but I would like you to open a proper issue.

**Comment by bochoven** [comment]
Hey Adam, any news?

**Comment by adambarnett52** [comment]
Hi

It fails time outs on the following

Request URL:https://maps.googleapis.com/maps/api/js?v=3.exp

and

Request URL:
https://km.support.apple.com.edgekey.net/kb/securedImage.jsp?configcode=E1D&size=240x240

Once it has time-out the client page loads correctly

Thanks
Adam

On Mon, Mar 7, 2016 at 4:55 PM, Arjen van Bochoven <notifications@github.com
> wrote:

> Hey Adam, any news?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/munkireport/munkireport-php/pull/420#issuecomment-193343162>
> .
>



-- 
Adam Barnett

**Comment by bochoven** [comment]
It looks like your firewall is dropping packets instead of refusing connections. Does running https://km.support.apple.com.edgekey.net/kb/securedImage.jsp?configcode=E1D&size=240x240 in the browser also hang up the browser?

**Comment by adambarnett52** [comment]
Yes, it just stays at connecting for a while and then timesout

On Mon, Mar 7, 2016 at 8:35 PM, Arjen van Bochoven <notifications@github.com
> wrote:

> It looks like your firewall is dropping packets instead of refusing
> connections. Does running
> https://km.support.apple.com.edgekey.net/kb/securedImage.jsp?configcode=E1D&size=240x240
> in the browser also hang up the browser?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/munkireport/munkireport-php/pull/420#issuecomment-193437329>
> .
>



-- 
Adam Barnett

**Pull request merged**
