### PR TITLE
Allow for graphs to have reversed colors

### PR DESCRIPTION
**Pull request by n8felton**
Before:

After:

### CODE REVIEW

**Comment by bochoven** [comment]
Ehh, why?

**Comment by n8felton** [comment]
Typically a gradient spectrum like this is cool to hot to show "good" to "bad" The more orange/red something is, the worse it is. This helps to show that machines at 7 years old are "worse" than machines at <1 year old.

**Comment by n8felton** [comment]
The "OS breakdown" widget could probably benefit from this as well.

**Comment by bochoven** [comment]
I think you'll need a different color scheme, the current one just rotates over the whole visible spectrum

**Comment by bochoven** [comment]
Thanks!

**Pull request merged**
