### PR TITLE
config_default.php Cleanup

### PR DESCRIPTION
**Pull request by kevinmcox**
Cleaned up a handful of spacing issues, related to the use of spaces vs. tabs, that weren't obvious in the GitHub views.

### CODE REVIEW

**Comment by kevinmcox** [comment]
And it looks like I did something wrong since it isn't just the commits I made showing in the PR...

**Comment by bochoven** [comment]
I think you'd better fork again

**Comment by bochoven** [comment]
Detectx lives in it's own repo now 

https://github.com/munkireport/detectx

**Comment by kevinmcox** [comment]
My Git inexperience is showing through. I didn't mean to include all those commits by you.

**Comment by kevinmcox** [comment]
I'll give it another shot after lunch.

**Pull request closed without merging**
