### PR TITLE
Help button addition

### PR DESCRIPTION
**Pull request by danner26**
Issue #1033 
Added a help button. If you do not define the help_url config it will not show the help button.
Otherwise, it will redirect to the URL specified or to the GitHub Wiki if left as a blank string.

$conf['help_url'] = ''; <--- Blank string will redirect to MunkiReport-PHP's GitHub Wiki
$conf['help_url'] = 'https://path/to/help'; <--- Will redirect to the path specified
No $conf['help_url'] will cause the help button to disappear.

### CODE REVIEW

**Comment by ofirgalcon** [comment]
Great! I will test and update you. Thanks

**Comment by danner26** [comment]
did everything work for you?

**Comment by ofirgalcon** [comment]
@danner26 I am pretty stupid here, still trying to figure how to download patches using git. On my to do list...

**Comment by danner26** [comment]
Simple, (on a test instance, do not do this on your production instance) do the following:
git fetch origin pull/1041/danner26:helpbutton-1033
git checkout helpbutton-1033

I think that'll do the job

**Comment by ofirgalcon** [comment]
Thanks!

I will be trying a bunch of modules over the next few days.

**Comment by danner26** [comment]
Did this work for you?

**Comment by ofirgalcon** [comment]
No, sorry I got an error. I'm sure it's because I'm missing a command, but which one:

bash-3.2# git fetch origin pull/1041/danner26:helpbutton-1033
fatal: Couldn't find remote ref pull/1041/danner26

**Comment by mosen** [comment]
Did a quick pull and check. Looks good danner26!

**Pull request merged**
