### PR TITLE
Better detection of Server app

### PR DESCRIPTION
**Pull request by gdarm**
Existing Server app does not indicate a running server, but launchctl knows.

### CODE REVIEW

**Comment by gdarm** [comment]
now it's a good pull request. ;)

**Comment by bochoven** [comment]
PR is fine! Did you test this on  10.6 and up?  I don't have Mac OS X server before 10.9

**Comment by gdarm** [comment]
Currently not. But the old one doesn't support 10.6 too...
On Monday I can test this with a 10.6 Srv VM. :)

**Comment by bochoven** [comment]
Not sure what the requirements should be.. I'm not using it due to not having OSX servers

**Comment by gdarm** [comment]
The path of the Server app is different from the script. The services are also different.

**Pull request closed without merging**
