### PR TITLE
App Version Reporting Page

### PR DESCRIPTION
**Pull request by rsaeks**
Includes updates for Awesome Font to 4.2 and adds in a reporting page
for app versions as well as an app widget to customize additional
applications.

### CODE REVIEW

**Comment by gmarnin** [comment]
@bochoven What is holding up this PR?

**Comment by bochoven** [comment]
@gmarnin not sure, I haven't looked at it. @nbalonso had some issues, I could not tell if they were all resolved.

**Comment by bochoven** [comment]
I can't merge it in the current state, I think it's because of the changes to config_default.php.

**Comment by clburlison** [comment]
I was able to test this feature last week and had no issues with this module. The branch will need to be synced before merging. 

Clayton Burlison

**Comment by rsaeks** [comment]
All sync'd on my side. Thank you!

**Pull request closed without merging**
