### PR TITLE
Change favicon to colored blocks

### PR DESCRIPTION
**Pull request by tuxudo**
Changed favicon to use a colored blocks style based off of the colored block widget on the dashboard

### CODE REVIEW

**Comment by tuxudo** [comment]
Colored Blocks

**Comment by WardsParadox** [comment]
While I do love (and hate think tombstone 😆 ) the logo I made, I think for a favicon, bookmark icon, etc it's not as clear at smaller sizes. Has my vote!

**Comment by bochoven** [comment]
Why the numbers?

**Comment by WardsParadox** [comment]
I think the numbers represent the data that you get on the dashboards.

**Comment by tuxudo** [comment]
@WardsParadox is correct. Just numbers showing what the colored blocks can look like

**Comment by bochoven** [comment]
If we're going to change the icon, I would prefer something else! 😄

**Pull request closed without merging**
