### PR TITLE
Add Issues/warning button to DetectX Module

### PR DESCRIPTION
**Pull request by precursorca**
Added an orange/issues warning button in addition to the already existing
infections/danger button and  clean/success button. Also moved clean/success green button to the
right side so the colors appear red-orange-green from left to right similar to other widgets. If there are issues only then Issues button is incremented. If there are infections only then Infections button is incremented. If there are issue AND infections then Infections button is incremented. No issues + no infections means that the Clean button is incremented.

### CODE REVIEW

**Comment by precursorca** [comment]
First fork/pull request. Hope I didn't screw this up too badly...

**Comment by bochoven** [comment]
Please send pull requests against the wip branch

**Comment by precursorca** [comment]
Thanks,

Was just following the DetectX module author recommendations (Zack McCauley) but I must have screwed it up.

I will try to figure out how to pull against wip branch.


---
Alex Narvey
anarvey@precursor.ca <mailto:anarvey@precursor.ca>

**Comment by precursorca** [comment]
Requested edit to move to wip branch

**Comment by precursorca** [comment]
Well I tried to do it against wip branch but I think I may have made it worse! So confusing.

---
Alex Narvey
anarvey@precursor.ca <mailto:anarvey@precursor.ca>

**Pull request closed without merging**
