### PR TITLE
Add iCloud module

### PR DESCRIPTION
**Pull request by tuxudo**
Supports multiple iCloud accounts on in all user home folders,
10.7-10.13+

### CODE REVIEW

**Comment by ofirgalcon** [comment]
Works for me. Very useful.

**Comment by bochoven** [comment]
Big PR, please test and report back. Does this still work in Mojave?

**Comment by tuxudo** [comment]
Just tested in 10.14 build 18A371a. Module needs some updating to work with new iCloud synced part of 10.14 and new defaults of unset iCloud services, but works otherwise. Should not be merged until full 10.14 compatibility is added

**Comment by tuxudo** [comment]
Closing PR, moved to module repo

**Pull request closed without merging**
