### PR TITLE
Add TeamViewer module

### PR DESCRIPTION
**Pull request by tuxudo**
Created TeamViewer module, by request of @ofirgalcon Slack

### CODE REVIEW

**Comment by ofirgalcon** [comment]
Works! Great work, thank you.

**Comment by bochoven** [comment]
Could you resolve the conflicts?

**Comment by tuxudo** [comment]
Conflicts resolved

**Comment by ofirgalcon** [comment]
if TV ID changes on the computer for some reason, the change is not shown in MR. This seems to happen after a user migrates to a new computer using Apple Migration Utility.

**Comment by tuxudo** [comment]
Bug should be fixed now. Added missing script block

**Comment by tuxudo** [comment]
Closing PR, moved to module repo

**Pull request closed without merging**
