### PR TITLE
Eloquent models PREVIEW

### PR DESCRIPTION
**Pull request by mosen**
!! DO NOT MERGE !!

Hi Bochoven,
This branch includes all new Eloquent models under the Mr\ namespace.
It also includes Faker configuration for generating databases full of fake reports.
A few modules have changed to use the Eloquent models but this has not been finalised.

### CODE REVIEW

**Comment by mosen** [comment]
The following controllers are affected:
```
certificate_controller.php
displays_info_controller.php
gpu_controller.php
homebrew_controller.php
homebrew_info_controller.php
managedinstalls_controller.php
usb_controller.php
wifi_controller.php
```

**Comment by mosen** [comment]
Machine group filter not yet applied to these queries

**Comment by mosen** [comment]
Machine group filter applied to Eloquent but not DB Query Builder.
ManagedInstalls requires testing.

**Comment by bochoven** [comment]
Eloquent models are partially implemented

**Pull request closed without merging**
