### PR TITLE
macOSLAPS module CSS and config_default

### PR DESCRIPTION
**Pull request by tuxudo**
Module contains all needed scripts, securely stores password, verifies password is stored on server then deletes local cached plaintext copy, uses Joshua Miller's macOSLAPS script.

### CODE REVIEW

**Comment by tuxudo** [comment]
To those that are testing this, you'll have to either drop and remake your database or manually add a column for the audit data.

**Comment by bochoven** [comment]
This is a large PR, hopefully some people can test it and report back.

**Comment by childrss** [comment]
Working on testing, adding some potential code... THANK YOU!!!

**Comment by bochoven** [comment]
Not sure what you are trying to do, but things went south here I think

**Comment by tuxudo** [comment]
Was trying to fix the conflict with config_default.php. Not exactly sure how it did what it did. I'll add it to the list of reasons why I don't like git.

**Comment by tuxudo** [comment]
Removed module and changed PR to add required CSS and config_default.php options

**Pull request closed without merging**
