### PR TITLE
Munkireportinfo version on Lion fix

### PR DESCRIPTION
**Pull request by tuxudo**
Defaults sometimes doesn't write out the version. Corrected by checking for version key and setting if doesn't exist

### CODE REVIEW

**Comment by bochoven** [comment]
I don't think I understand what you're doing and why?

**Comment by tuxudo** [comment]
If a client doesn't have the version key in the MunkiReport.plist, MySQL will error because it's trying to set an INT to NULL. This corrects that by setting it to a fake null which is then blanked on the listing and client tab.

**Comment by bochoven** [comment]
But why set it to -9876543 instead of 0?

**Comment by tuxudo** [comment]
A INT that should rarely, if ever, actually be set. That way the UI views don't blank out actual data

**Comment by bochoven** [comment]
Tx!

**Pull request merged**
