### PR TITLE
Add Jamf module

### PR DESCRIPTION
**Pull request by tuxudo**
Adds support for pulling data from a Jamf/JSS server

### CODE REVIEW

**Comment by tuxudo** [comment]
Modular admin views split into separate PR #1134. For full functionality, module requires PR #1134

**Comment by bochoven** [comment]
Large PR, I'm not going to use it. Anyone care to review it?

**Comment by bochoven** [comment]
This PR has conflicts, please resolve

**Comment by tuxudo** [comment]
This PR needs broken out into a module repo. Haven't had time to do that yet.

**Comment by bochoven** [comment]
What is the status of this PR? Do you still want it merged? I assume it needs some modernising.

**Comment by tuxudo** [comment]
It needs a lot of work to get it updated. I'm been very busy with little extra energy for side projects as of late. It's mostly here and open as a reminder for me to break it off into its own module.

**Comment by tuxudo** [comment]
Module updated and moved to its own repo  🎉

**Pull request closed without merging**
