### PR TITLE
Updated German translation for GSX, Location and WiFi modules

### PR DESCRIPTION
**Pull request by fridomac**
Added the missing words, hope there are no typos anymore...:-)

Bye, Frido

### CODE REVIEW

**Comment by bochoven** [comment]
You missed a couple of comma's, please look here: https://github.com/munkireport/munkireport-php/pull/421/files#diff-0

The safest way to translate is to use the online translation tool: http://i18next-editor.herokuapp.com. You paste en.json in the left side and de.json in the right side. Then you press 'Generate input fields '. After you're finished, you press 'Generate JSON' and you have a perfectly formatted json text block.

**Comment by fridomac** [comment]
Oh sorry, that´s what you get for rushing things... 
Thanks for the link to the editor, simplifies things greatly! (you mentioned it last time, but just tried it now)

Do I have to make a new pull request?

Bye, Frido.

**Comment by bochoven** [comment]
I think you can just update the files

**Comment by bochoven** [comment]
Maybe you can set yourself as author in stead of me

**Comment by fridomac** [comment]
Ok, changed the author field and updated the file. Thank your for the help!

**Comment by bochoven** [comment]
Thnx!

**Pull request merged**
