### PR TITLE
Fix Apple SoftwareUpdate identifier in munkiinfo.py script

### PR DESCRIPTION
**Pull request by MichalMMac**
I noticed there is no AppleCatalogURL beeing reported in munkiadmin-php 2.8.4 even thought I set one.

There was problem with identifier being `com.apple.softwareupdate` instad of `com.apple.SoftwareUpdate`. Upper case does seem to matter.

    > defaults read /Library/Preferences/com.apple.SoftwareUpdate CatalogURL 
    http://1.2.3.4:1234/index_production.sucatalog
    > python
    >>> from Foundation import CFPreferencesCopyAppValue
    >>> AppleCatalogURL = str(CFPreferencesCopyAppValue('CatalogURL', 'com.apple.softwareupdate'))
    >>> print AppleCatalogURL 
    None
    >>> AppleCatalogURL = str(CFPreferencesCopyAppValue('CatalogURL', 'com.apple.SoftwareUpdate'))
    >>> print AppleCatalogURL
    http://1.2.3.4:1234/index_production.sucatalog

### CODE REVIEW

**Comment by erikng** [comment]
What OS did you experience this with? Apple did make a change and perhaps instead of changing this explicitly, we need to set some conditions.

**Comment by MichalMMac** [comment]
Terminal output is from 10.11.4. Clients not reporting AppleCatalogURL are 10.10.5.

**Comment by MichalMMac** [comment]
After OS reboot on my 10.11.4 MacBook both  'com.apple.softwareupdate'  and 'com.apple.SoftwareUpdate' work.

When I change CatalogURL with defaults command i get this:

```
> defaults read /Library/Preferences/com.apple.SoftwareUpdate.plist CatalogURL
http://1.2.3.4:1234/index_production.sucatalog
> sudo defaults write /Library/Preferences/com.apple.SoftwareUpdate CatalogURL 
http://4.3.2.1:9999/index_production.sucatalog
>>> AppleCatalogURL = str(CFPreferencesCopyAppValue('CatalogURL', 'com.apple.softwareupdate'))
>>> print AppleCatalogURL                                                       
http://1.2.3.4:1234/index_production.sucatalog
>>> AppleCatalogURL = str(CFPreferencesCopyAppValue('CatalogURL', 'com.apple.SoftwareUpdate'))
>>> print AppleCatalogURL                                                       
http://4.3.2.1:9999/index_production.sucatalog
```

 Maybe caching issue with cfprefsd?

Function with `com.apple.SoftwareUpdate` works consistently.

**Comment by clburlison** [comment]
I tested this in 10.9.5, 10.10.5, and 10.11.4 all with correct values being returned via `com.apple.SoftwareUpdate` and `com.apple.softwareupdate`. I don't see an issue with changing the case to the capitalized version though I'm still unsure which is the preferred version or if case even matters.

**Comment by bochoven** [comment]
So this is not an issue?

**Comment by clburlison** [comment]
For what it's worth Munki is using the capitalized version. So with that I'd recommend resubmitting this PR against the `wip` branch.

```bash
munkilib/appleupdates.py
86:APPLE_SOFTWARE_UPDATE_PREFS_DOMAIN = 'com.apple.SoftwareUpdate'
699:        # Otherwise prefer MCX or /Library/Preferences/com.apple.SoftwareUpdate
985:        """Returns a preference from com.apple.SoftwareUpdate.
1031:                    'Error setting com.apple.SoftwareUpdate CatalogURL.')
1090:                'Error resetting com.apple.SoftwareUpdate CatalogURL.')
1111:                'Error setting com.apple.SoftwareUpdate ByHost preferences.')
1736:                "remove this setting and use com.apple.SoftwareUpdate's "
```

I was still unable to replicate the initial issue.

**Comment by MichalMMac** [comment]
Ok. Resubmited against `wip` as #469.
Closing this one.

**Pull request closed without merging**
