### PR TITLE
Detailed Dashboard widget layout

### PR DESCRIPTION
**Pull request by erikng**
Define each widget's size and how it works in the responsive design.

### CODE REVIEW

**Comment by bochoven** [comment]
I appreciate the effort, but be aware that I am planning to move to another frontend in the (hopefully) near future.

**Comment by erikng** [comment]
Is there a branch I can pull into another VM to test?

This is only my second day using MR and I sadly haven't kept up with your project.

**Comment by bochoven** [comment]
Actually it is not more than a plan...

**Comment by erikng** [comment]
Ah no problem. I have an idea already. Perhaps I will email you. 

Do you get on IRC? I've never seen you there.

**Pull request merged**
